### ISSUE TITLE
issue with a song

### ISSUE THREAD

**Issue by droidmjt** [BouKiCHi/mdxplayer#8]
Hello,
here is a song that makes mdxplayer skip some events at the beginning. You should hear fade-in (or similar effect) at the beginning but somehow it get's skipped.

https://www.dropbox.com/s/tp4cy36aag5tp25/SGOP.mdx?dl=0

**Comment by BouKiCHi** [comment]
Hi,
I tried to fix this problem, but failure to fix.
It seems a part of software lfo is missing in the code.

If you would like to play mdx files in a command line,
the following might be helpful. 

https://www.dropbox.com/s/7jucod6uxzmsjho/gamdx_sdl_150512_src.zip?dl=0

**Comment by droidmjt** [comment]
all right, i will try it, thank you :)

**Comment by droidmjt** [comment]
could you check the sdlmain.c for PDX loading, it doesn't seem to work. I checked how it is done in mxp.cpp but it didn't help :(

**Comment by droidmjt** [comment]
ftp://ftp.modland.com/pub/modules/MDX/After%20Burner/ab2-bfd.mdx
ftp://ftp.modland.com/pub/modules/MDX/After%20Burner/ab2.pdx

**Comment by droidmjt** [comment]
Additional links:
https://www.dropbox.com/s/m469l6fb375x0bo/ab2-bfd.mdx?dl=0
https://www.dropbox.com/s/9kz43ngicx3444e/ab2.pdx?dl=0

**Comment by BouKiCHi** [comment]
I tried ab2-bfd.mdx,
It seems playable but indeed some part of track wrong.

If you have problem for PDX loading and you tried it in case-sensitive file system,
it might be mismatch between written filename in MDX and filename of PDX in folder.

**Comment by droidmjt** [comment]
there is no mismatch, check the sdlmain.c code, it doesn't even open pdx file for reading..see below

FILE *fin = NULL;
havepdx = 0;

if ( havepdx ) 
{
    fseek( fin, 0, SEEK_END ); 
.......
}
fin variable is not used for opening the pdx file anywhere. I'm trying to use this on Android as a library.

**Comment by droidmjt** [comment]
a sidenote, i tried the command line player (mxp.exe) to play that ab2-bfd.mdx song, the pdx stuff still sounds like crap, it seems that the guy who wrote the foo_input_mdx plugin managed to make the gorry library work properly.

http://www.vesta.dti.ne.jp/~tsato/soft_fb2k.html

if you know that guy, ask source for the foo mdx plugin :) :)

**Comment by droidmjt** [comment]
https://www.dropbox.com/s/7jucod6uxzmsjho/gamdx_sdl_150512_src.zip?dl=0

any chance you could fix that PDX loading/handling in the source above?

**Comment by BouKiCHi** [comment]
it’s off topic.

**Comment by droidmjt** [comment]
ok i create a new topic, sorry :)
