### ISSUE TITLE
problems with PDX loading and handling

### ISSUE THREAD

**Issue by droidmjt** [BouKiCHi/mdxplayer#9]
https://www.dropbox.com/s/7jucod6uxzmsjho/gamdx_sdl_150512_src.zip?dl=0

any chance you could fix that PDX loading/handling in the source above?

**Comment by BouKiCHi** [comment]
As a player for MDX on Android,  
http://gorry.haun.org/android/gamdx/#download
This is the original and same as the source code.

As a player on console,
I have no plan to port it.

**Comment by droidmjt** [comment]
nobody is talking about consoles, im talking about the PDX (sample data file) loading and handling.

**Comment by BouKiCHi** [comment]
*console = command line (CLI application)

the source code is from gamdx and I have no plan to modify it.

**Comment by droidmjt** [comment]
ah, hehe, all right, my bad :)

**Comment by droidmjt** [comment]
could you at least check the sdlmain.c code, i believe it was written by you.

**Comment by BouKiCHi** [comment]
No.
Firstly, that source code is not related to this project as I mentioned.
Secondly, I refuse to help one who a person to use "the guy" to mention my acquaintance.

Anyway, I decide to remove this project from github.
